services:
  - type: web
    name: wolvcapital
    runtime: python
    healthCheckPath: /healthz/
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: bash start.sh
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: DJANGO_SETTINGS_MODULE
        value: "wolvcapital.settings"
      - key: WEB_CONCURRENCY
        value: "2"
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: wolvcapital-db
          property: connectionString
      - key: SENDGRID_API_KEY
        value: ""  # Set this in Render Dashboard Environment Variables
      - key: DEFAULT_FROM_EMAIL
        value: "noreply@wolvcapital.com"

databases:
  - name: wolvcapital-db
    databaseName: wolvcapital
    user: wolvcapital
